// <auto-generated />
using GA.Fazenda.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GA.Fazenda.Data.Migrations
{
    [DbContext(typeof(FazendaContexto))]
    [Migration("20220316200308_Start")]
    partial class Start
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("GA.Fazenda.Business.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FazendaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("FazendaId");

                    b.ToTable("Animal");
                });

            modelBuilder.Entity("GA.Fazenda.Business.Models.EntidadeFazenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Fazenda");
                });

            modelBuilder.Entity("GA.Fazenda.Business.Models.Animal", b =>
                {
                    b.HasOne("GA.Fazenda.Business.Models.EntidadeFazenda", "Fazenda")
                        .WithMany("Animais")
                        .HasForeignKey("FazendaId")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
